### PR TITLE
[Nicole] move 2 songs to A Little Peace (album)

### PR DESCRIPTION
**Pull request by andy5995**

### CODE REVIEW

**Comment by snshn** [comment]
You can also just keep more than one file for the same text if it appears on more than one album, as long as they're not symlinks

**Review by snshn — APPROVED** [review]

**Comment by andy5995** [comment]
> You can also just keep more than one file for the same text if it appears on more than one album, as long as they're not symlinks

Ok, I'll do that. That can help prevent dead links I think.

**Comment by snshn** [comment]
Yeah, and it's not just dead links — sometimes people may think that the lyrics is missing if they only look for it in one album, while it exists but inside of another one. Too bad symlinks is such a mess, but duplicates are rather rare.

**Comment by andy5995** [comment]
> Yeah, and it's not just dead links — sometimes people may think that the lyrics is missing if they only look for it in one album, while it exists but inside of another one. Too bad symlinks is such a mess, but duplicates are rather rare.

Related discussion started in https://github.com/Lyrics/lyrics/discussions/521

**Pull request merged**
