### PR TITLE
[結束バンド] Add Album "結束バンド"

### PR DESCRIPTION
**Pull request by Starman-x64**
Added 14 Songs by 結束バンド:
1. 青春コンプレックス
2. ひとりぼっち東京
3. Distortion!!
4. ひみつ基地
5. ギターと孤独と蒼い惑星
6. ラブソングが歌えない
7. あのバンド
8. カラカラ
9. 小さな海
10. なにが悪い
11. 忘れてやらない
12. 星座になれたら
13. フラッシュバッカ―
14. 転がる岩、君に朝が降る

### CODE REVIEW

**Comment by snshn** [comment]
Hey!  Thank you for the contribution!

we'll probably need to have two spaces after every metadata key,  I just glanced at the code before running the CI check.

also, file names probably better be lower-case, I'm thinking that capitalization is good for styling in HTML but makes it harder to read file and directory names when browsing via terminal/filemanager

**Comment by Starman-x64** [comment]
Alright, everything should be updated now with two-spaces after each key and lowercase titles.

**Comment by snshn** [comment]
Everything looks good, thank you for updating it.

It looks like I need to change one of the tests to ignore Japanese artist names when it comes to matching their first letters with their parent (group) folders.

Once I'm done updating that, I will merge this PR in and the lyrics will be available on the site.

**Comment by snshn** [comment]
Just merged everything in, thank you again for your contribution.

I will take care of any issues from within the master branch.

**Pull request merged**
