### PR TITLE
[Have A Nice Life] add Deathconsciousness

### PR DESCRIPTION
**Pull request by egecelikci**
This album actually consists of 2 discs (2×CD-R, 7 + 6), but I didn't know how to number the disc and track numbers.
```
Name            Waiting for Black Metal Records to Come in the Mail
Artist          Have A Nice Life
Album           Deathconsciousness
Disc no         2
Track no        8
```
or
```
Name            Waiting for Black Metal Records to Come in the Mail
Artist          Have A Nice Life
Album           Deathconsciousness
Disc no         2
Track no        1
```
The 2nd is the correct usage according to the examples I have compared from the database and MusicBrainz, but I'm still not sure how it will look on the site, or will it conflict with the 1st track of the first disc. However, since the album has a digital version of 13 tracks, I did not see any harm in not including disc no.

### CODE REVIEW

**Comment by egecelikci** [comment]
Hmm, what should I use instead of (`:`) colon

**Comment by snshn** [comment]
Hey, thank you for such a big addition!

` - ` to be used instead of `: ` is the best I could find myself so far — that's how movie and music names get altered for filesystems that don't support colons.

The `Disc no` is a rather new feature, I needed some material before I could add proper rendering for it on the website; this PR seems to be adding enough of that, now I'll be able to implement it in the website generator.

Could you please specify if the language is `American English` or `British English` in the meta section? It'd be best to be specific with that one, as once something like spell check is in place, we could automate proof-reading.

**Comment by snshn** [comment]
I'll go ahead and patch the website generator to group items by disc number

**Comment by snshn** [comment]
There you go friends, https://lyrics.github.io/db/H/Have%20A%20Nice%20Life/Deathconsciousness/

**Pull request merged**
