### PR TITLE
[mxmtoon] Add dusk album

### PR DESCRIPTION
**Pull request by TurboWafflz**
I'm not entirely sure if I've done the capitalization right. All of the information is lowercase in the actual names, but I don't know if i should be capitalized for this repository.

### CODE REVIEW

**Comment by snshn** [comment]
Bey there!  Thank you for the submission!

This looks great, just needs some tweaks:

1. Metadata needs to be separated from keys by at least two spaces, not tabs
2. It's better to capitalize directory and file names to be make them more readable.  Values from metadata will be used for labels on the website, while directory and file names are there to construct the URLs, and those ideally should never change or be stylized.
3. Apostrophes and quotation marks should ideally be using proper typographical symbols, more info here: https://smartquotesforsmartpeople.com/

**Comment by TurboWafflz** [comment]
Ok, I think I implemented all of those changes properly now

**Comment by snshn** [comment]
Thank you for fixing those!

It looks like items under `M/mazie/` are files, and texts always need to belong to a release of sorts in this database in order to keep the structure consistent, e.g. `M/Mazie/Some Album Name/Some Song Name`

**Comment by TurboWafflz** [comment]
Oops, that folder wasn't supposed to be in the pull request. I completely forgot I had created it and accidentally committed it. It's gone now

**Comment by TurboWafflz** [comment]
Looks like it failed the windows test because it doesn't like dots in paths. Should be fixed now

**Comment by snshn** [comment]
Thank you for fixing it!  Yes, Windows has a lot of weird limitations, e.g. no colons in file names.

**Pull request merged**
