### PR TITLE
[Nicole]add Where Have All My Heroes Gone

### PR DESCRIPTION
**Pull request by andy5995**
Missing one line. Can anyone make out the words between 2m:45s and 2m:50s?

https://www.youtube.com/watch?t=165&v=mHOlfcmFizE&feature=youtu.be

### CODE REVIEW

**Comment by andy5995** [comment]
> Missing one line. Can anyone make out the words between 2m:45s and 2m:50s?
> 

A friend of mine helped me complete this. Ready for review.

**Comment by andy5995** [comment]
Oh, I think it's correct that I set the album as 'Butterfly'. This song was the B side.

**Comment by snshn** [comment]
If a bit is missing, I usually try to find live recordings; sometimes you can find scans of lyrics inserts or LP covers that contain lyrics on ebay or discogs. Glad your friend was able to help with that missing piece.

> From the kingdom of fantasy
> They just faded away

sounds right to me

**Comment by andy5995** [comment]
> If a bit is missing, I usually try to find live recordings; sometimes you can find scans of lyrics inserts or LP covers that contain lyrics on ebay or discogs. Glad your friend was able to help with that missing piece.

Thanks for the tip, I'll keep that in mind.

**Pull request merged**
